// Fill out your copyright notice in the Description page of Project Settings.


#include "Uzuha.h"
#include "Camera/CameraComponent.h"
#include "GameFramework/CharacterMovementComponent.h"
#include "GameFramework/SpringArmComponent.h"
#include "UzuhaController.h"
#include "Kismet/GameplayStatics.h"
#include "UzuhaController.h"
#include "Blueprint/UserWidget.h"
#include "Components/SkeletalMeshComponent.h"
#include "Animation/UzuhaAnimInstance.h"
#include "EngineUtils.h"
// FOW
#include "MathUtil.h"
// Sets default values
#include "Components/AnimationControlComponent.h"
#include "NiagaraFunctionLibrary.h"

#include "WASDL/Enemy/BaseEnemy.h"

// Widget
#include "Actor/OrderWidgetActor.h"
#include "Blueprint/WidgetLayoutLibrary.h"
#include "Components/HealthComponent.h"
#include "Components/SoundComponent.h"
#include "Components/WidgetComponent.h"
#include "Engine/SkeletalMeshSocket.h"
#include "Kismet/KismetMathLibrary.h"
#include "Net/UnrealNetwork.h"
#include "WASDL/Actor/CommandCenter.h"
#include "WASDL/Actor/PingActor.h"
#include "WASDL/System/TeamPlayerState.h"
#include "WASDL/System/Audio/AudioManagerSubsystem.h"
#include "WASDL/System/FOW/FogOfWarSubsystem.h"
#include "WASDL/System/FOW/FogVisibilityComponent.h"
#include "WASDL/System/FOW/VisionRevealerComponent.h"
#include "WASDL/Widgets/CursorWidget.h"
#include "WASDL/Widgets/OrderWidget.h"
#include "WASDL/Widgets/PlayerWidget.h"
#include "WASDL/Widgets/EnemyHealthWidget.h"
#include "WASDL/Widgets/PlayerListWidget.h"

AUzuha::AUzuha()
{
	// Set this character to call Tick() every frame.  You can turn this off to improve performance if you don't need it.
	PrimaryActorTick.bCanEverTick = true;
	bReplicates = true;
	//bReplicateMovement = true;
	//SetReplicates(true);
	//bCanBeDamaged = true;
	SetCanBeDamaged(true);
	//SetReplicateMovement(true);
	
	//bOnlyRelevantToOwner = false; // ì†Œìœ ì ê´€ë ¨ì„± ë„ê¸° (ì›ê²© í´ë¼ì— ì•ˆë³´ì„)
	
	NetUpdateFrequency = 30.f;
	MinNetUpdateFrequency = 15.f;
	
	// ì»¨íŠ¸ë¡¤ëŸ¬ íšŒì „ì€ ì‚¬ìš©í•˜ì§€ ì•ŠìŒ (íƒ‘ë·°ìš©)
	bUseControllerRotationPitch = false;
	bUseControllerRotationYaw = false;
	bUseControllerRotationRoll = false;

	CameraPivot = CreateDefaultSubobject<USceneComponent>(TEXT("CameraPivot"));
	CameraPivot->SetupAttachment(RootComponent);

	SpringArm = CreateDefaultSubobject<USpringArmComponent>(TEXT("SpringArm"));
	SpringArm->SetupAttachment(CameraPivot);
	SpringArm->TargetArmLength = DefaultSpringArm;
	SpringArm->SetRelativeRotation(FRotator(-40.f, 0.f, 0.f));
	SpringArm->SetUsingAbsoluteRotation(true); // ì»¨íŠ¸ë¡¤ëŸ¬ íšŒì „ì— ì˜í–¥ë°›ì§€ ì•Šê²Œ
	SpringArm->bUsePawnControlRotation = false;
	SpringArm->bDoCollisionTest = false;

	Camera = CreateDefaultSubobject<UCameraComponent>(TEXT("Camera"));
	Camera->SetupAttachment(SpringArm);
	Camera->bUsePawnControlRotation = false;

	
	// ì´ë™ ë°©í–¥ì„ ë°”ë¼ë³´ë„ë¡
	auto* Move = GetCharacterMovement();
	//Move->SetMovementMode(MOVE_Walking);
	Move->MaxWalkSpeed = 600.f;
	Move->bOrientRotationToMovement = true; // ê¸°ë³¸ ì´ë™ë°©í–¥ ë°”ë¼ë³´ê¸°
	Move->bUseControllerDesiredRotation = false; // ê¸°ë³¸ : ì»¨íŠ¸ë¡¤ëŸ¬ íšŒì „ ì‚¬ìš© X
	Move->RotationRate = FRotator(0.f, 720.f, 0.f);
	//Move->SetPlaneConstraintNormal(FVector::UpVector); // (0,0,1) â† ì´ê²Œ ì •ë‹µ
	// í˜¹ì‹œ ëª¨ë¥´ë‹ˆ ì›ì ë„ ì´ˆê¸°í™”
	//Move->SetPlaneConstraintOrigin(FVector::ZeroVector);
	//Move->bConstrainToPlane = false;
	
	// íƒ‘ë·° í‰ë©´ ì œì•½ ì“°ë ¤ë©´ â€˜Zâ€™ë¡œ!
	Move->SetPlaneConstraintAxisSetting(EPlaneConstraintAxisSetting::Z);  // ì¶• ê³ ì •
	// ìŠ¤í”„ë§ì•” + ì¹´ë©”ë¼ (íƒ‘ë·° ê°ë„)
	HealthComponent = CreateDefaultSubobject<UHealthComponent>(TEXT("HealthComponent"));
	VisibilityComponent = CreateDefaultSubobject<UFogVisibilityComponent>(TEXT("VisibilityComponent"));
	VisionRevealerComponent = CreateDefaultSubobject<UVisionRevealerComponent>(TEXT("VisionRevealer"));
	VisionRevealerComponent->SetupAttachment(RootComponent);
	
	SoundComponent = CreateDefaultSubobject<USoundComponent>(TEXT("SoundComponent"));
		
	HealthWidget = CreateDefaultSubobject<UWidgetComponent>(TEXT("HPBarWidget"));
	HealthWidget->SetupAttachment(RootComponent);
	
	HealthWidget->SetWidgetSpace(EWidgetSpace::World); // ì›”ë“œ ê³µê°„ ìœ ì§€
	HealthWidget->SetDrawSize(FVector2D(128,10));
	//HealthWidget->SetDrawAtDesiredSize(true);
	HealthWidget->SetWidgetClass(HealthWidgetClass);
	//HealthWidget->SetWidgetClass(HealthWidgetClass);
	HealthWidget->SetTwoSided(true); // í•„ìš” ì‹œ ì–‘ë©´ ë Œë”
	HealthWidget->SetUsingAbsoluteRotation(true); // ì•¡í„° íšŒì „ ì˜í–¥ ì œì™¸(ê¶Œì¥)

	// â˜… ê°€ì‹œì„±/ì†Œìœ ì í”Œë˜ê·¸ë¥¼ ëª¨ë‘ í•´ì œ (ëˆ„êµ¬ì—ê²Œë‚˜ ë³´ì´ë„ë¡)
	HealthWidget->SetHiddenInGame(false);
	HealthWidget->SetVisibility(true, true);
	HealthWidget->SetOnlyOwnerSee(false);
	HealthWidget->SetOwnerNoSee(false);
	
	AnimationComponent = CreateDefaultSubobject<UAnimationControlComponent>(TEXT("AnimationComponent"));
	
	/*
	static ConstructorHelpers::FClassFinder<UCursorWidget> CursorBPClass(TEXT("/Game/Widgets/WBP_Cursor.WBP_Cursor_C"));
	if (CursorBPClass.Succeeded())
	{
		CursorWidgetClass = CursorBPClass.Class;
	}
	else GEngine->AddOnScreenDebugMessage(-1, 2.0f, FColor::Red, TEXT("[Uzuha] CursorWidget null"));
	*/
}

// Called when the game starts or when spawned
void AUzuha::BeginPlay()
{
	Super::BeginPlay();
	SetAttackModeLook(false);
	AnimInstance = Cast<UUzuhaAnimInstance>(GetMesh()->GetAnimInstance());

	if (HealthComponent)
	{
		HealthComponent->HealthInitialize(120.0f);
		//HealthComponent->
	}
	
	
	UGameplayStatics::GetAllActorsWithTag(GetWorld(), FName("CommandCenter"), CommandCenter);
	if (CommandCenter.Num() != 0)
	{
		CommandCenterInstance = Cast<ACommandCenter>(CommandCenter.IsValidIndex(0) ? CommandCenter[0] : nullptr);
		//GEngine->AddOnScreenDebugMessage(-1, 3.0F, FColor::Yellow,
		//                               FString::Printf(
		//	                                 TEXT("Get CommandCenter : %s"), *CommandCenterInstance->GetName()));
	}
	else
	{
		GEngine->AddOnScreenDebugMessage(-1, 3.0F, FColor::Red, TEXT("[Uzuha] CommandCenter"));
	}

	TWeakObjectPtr<AUzuha> Weak(this);
	GetWorld()->GetTimerManager().SetTimer(RegisterDelayHandle, [Weak,this]()
	{
		if (!Weak.IsValid())return;
		RegisterRevealer();
	}, 0.3,false);
	//GetWorld()->GetTimerManager().SetTimer(ListWidgetTimer, this, &AUzuha::ListWidgetInit, 1.0f, false);
}

void AUzuha::GetLifetimeReplicatedProps(TArray<class FLifetimeProperty>& OutLifetimeProps) const
{
	Super::GetLifetimeReplicatedProps(OutLifetimeProps);
	DOREPLIFETIME_CONDITION(AUzuha, ReplicatedAimYaw,COND_SkipOwner); // ì†Œìœ ìì—ê²Œ ë¶ˆí•„ìš”í•œ ë³µì œ ì°¨ë‹¨í•¨
	//DOREPLIFETIME(AUzuha, CurrentHP);
	//DOREPLIFETIME(AUzuha, bIsDead);
}

float AUzuha::TakeDamage(float DamageAmount, struct FDamageEvent const& DamageEvent, class AController* EventInstigator,
	AActor* DamageCauser)
{
	if (//!HasAuthority() ||
		HealthComponent->bIsDead) return 0.0f;
	
	const float OldHP = HealthComponent->CurrentHP;

	HealthComponent->CurrentHP = FMath::Clamp(HealthComponent->CurrentHP - DamageAmount, //FMath::Max(0.f, DamageAmount),
							 0.f,
							 HealthComponent->MaxHP);


	if (GetNetMode() == NM_ListenServer)
	{
		HealthComponent->OnRep_CurrentHP();
	}
	
	//HealthComponent->UpdateHealthUI();
	
	//GEngine->AddOnScreenDebugMessage(-1, 1.0f, FColor::Magenta, FString::Printf(TEXT("GetDamaged : %f"), HealthComponent->CurrentHP));
	/*
	ATeamPlayerState* PS = GetPlayerState<ATeamPlayerState>();
	if (PS)
	{
		const float NewHP = FMath::Clamp(PS->GetHealth() - DamageAmount, 0.f, 100.f);
		PS->SetHealth(NewHP, HealthComponent->MaxHP); // â†’ ëª¨ë“  í´ë¼ UIê°€ OnRepë¡œ ê°±ì‹ ë¨
	}
	*/
	
	if (HealthComponent->CurrentHP <= 0 && !HealthComponent->bIsDead)
	{
		HealthComponent->bIsDead = true;
		HandleDeath(); // ì„œë²„ì—ì„œë§Œ ì‹¤í–‰ë˜ê²Œ
		//MultiCast_OnDeath(); // FX ì• ë‹ˆë©”ì´ì…˜ ë¸Œë¡œë“œìºìŠ¤íŠ¸
	}
	
	return Super::TakeDamage(DamageAmount, DamageEvent, EventInstigator, DamageCauser);
}

void AUzuha::PossessedBy(AController* NewController)
{
	Super::PossessedBy(NewController);
	PC = Cast<AUzuhaController>(NewController);   // âœ… ì„œë²„ì—ì„œ ì¦‰ì‹œ ì—°ê²°
	//GEngine->AddOnScreenDebugMessage(-1, 2.0f, FColor::Green,
	//FString::Printf(TEXT("%s Controller  : %s"), *this->GetName(), *PC->GetName()));
	EnsureLocalUI();      // ë¡œì»¬ì´ë©´ UI ë³´ì¥
}

void AUzuha::OnRep_Controller()
{
	Super::OnRep_Controller();
	PC = Cast<AUzuhaController>(GetController());  // âœ… í´ë¼ì—ì„œ ë³µì œ ì™„ë£Œ ì‹œì ì— ì—°ê²°
	EnsureLocalUI();                               // ë¡œì»¬ì´ë©´ UI ë³´ì¥
}

// Called every frame
void AUzuha::Tick(float DeltaTime)
{
	Super::Tick(DeltaTime);
	UpdateAimRotation(); // ë§¤ í”„ë ˆì„ ì»¤ì„œ ë°©í–¥ìœ¼ë¡œ íšŒì „
	VisionRevealerComponent->SetWorldLocation(GetActorLocation());
	auto* Move = GetCharacterMovement();
	const float V = Move->Velocity.Size();
	const float A = Move->GetCurrentAcceleration().Size();
	const bool OnGround = Move->IsMovingOnGround();
	const auto Mode = Move->MovementMode;

	/*
	GEngine->AddOnScreenDebugMessage(11, 0.f, FColor::Cyan,
	  FString::Printf(TEXT("Vel=%.1f  Acc=%.1f  Mode=%d  OnGround=%d"),
	  V, A, (int)Mode, OnGround));
*/
	
	if (CameraPivot)
	{
		UpdateSpringArm(DeltaTime);
		//CameraPivot->UpdateCameraLocation(CameraPoint);
		if (bTargetCamOn)
		{
			SetNewCameraPivot();
		}
		else
		{
			CameraPoint = GetActorLocation();
		}
	}
	const FVector WidgetLoc = GetActorLocation() + FVector(0.f, 0.f, 150.f);
	HealthWidget->SetWorldLocation(WidgetLoc);
	FRotator rot = FRotator(180.f, 0.f, 0.f);
	HealthWidget->SetWorldRotation(rot.Quaternion());
	if (!PC) return;

	return;
	// 1) ìœ„ì¹˜ ì—…ë°ì´íŠ¸(ì´ë¯¸ í•˜ê³  ìˆë‹¤ë©´ ìœ ì§€)
	//const FVector WidgetLoc = GetActorLocation() + FVector(0.f, 0.f, 150.f);
	HealthWidget->SetWorldLocation(WidgetLoc);

	// 2) ì„œë²„ê°€ â€˜ì „ìš© ì„œë²„â€™ë©´ UI ë¶ˆí•„ìš” â†’ ìŠ¤í‚µ
	if (GetNetMode() == NM_DedicatedServer) return;

	// 3) ì´ í”„ë¡œì„¸ìŠ¤ì˜ â€˜ë¡œì»¬ í”Œë ˆì´ì–´ë“¤â€™ ì¤‘ ì¹´ë©”ë¼ ì„ íƒ
	APlayerCameraManager* BestCam = nullptr;
	float BestDistSq = TNumericLimits<float>::Max();

	for (FConstPlayerControllerIterator It = GetWorld()->GetPlayerControllerIterator(); It; ++It)
	{
		APlayerController* localPC = It->Get();
		if (!localPC || !localPC->IsLocalController()) continue; // ë¡œì»¬ë§Œ
		if (APlayerCameraManager* Cam = localPC->PlayerCameraManager)
		{
			const float DSq = FVector::DistSquared(HealthWidget->GetComponentLocation(), Cam->GetCameraLocation());
			if (DSq < BestDistSq)
			{
				BestDistSq = DSq;
				BestCam = Cam;
			}
		}
	}

	if (BestCam)
	{
		FRotator LookAt = UKismetMathLibrary::FindLookAtRotation(WidgetLoc, BestCam->GetCameraLocation());

		// í’€ ë¹Œë³´ë“œ
		// LookAt.Roll = 0.f;           // í•„ìš” ì‹œ ë¡¤ë§Œ ê³ ì •

		// Yaw-Only(ìƒí•˜ ê¸°ìš¸ì„ ì—†ì´ ìˆ˜í‰ë§Œ): ì›í•˜ë©´ ì•„ë˜ ë‘ ì¤„ ì‚¬ìš©
		// LookAt.Pitch = 0.f;
		// LookAt.Roll  = 0.f;

		// ìœ„ì ¯ ì•ë©´ì´ ë’¤ë¥¼ í–¥í•˜ë©´ 180ë„ ë³´ì •
		//LookAt.Yaw += 180.f;

		HealthWidget->SetWorldRotation(LookAt);
	}
}

void AUzuha::SetController(AUzuhaController* _Ctr)
{
	//GEngine->AddOnScreenDebugMessage(-1, 2.0f, FColor::White, TEXT("SetCtr"));
	PC = _Ctr; // ì €ì¥
	EnsureLocalUI(); // ë¡œì»¬ìƒíƒœë¼ë©´ UI ë³´ì¥
}

void AUzuha::UpdateAimRotation()
{
	if (!PC) return;
	if (!bRMPressed) return;
	if (PlayerState != EPlayerState::Attack) return;
	
	FVector MouseLocation, MouseDirection;
	// ğŸ”¹ ë§ˆìš°ìŠ¤ì˜ ì›”ë“œ ìœ„ì¹˜ì™€ ë°©í–¥ì„ ì–»ê¸°
	if (PC->DeprojectMousePositionToWorld(MouseLocation, MouseDirection))
	{
		FHitResult HitResult;
		FVector End = MouseLocation + (MouseDirection * 10000.0f);

		// ğŸ”¹ ë§ˆìš°ìŠ¤ ë°©í–¥ìœ¼ë¡œ ë ˆì´ìºìŠ¤íŠ¸í•˜ì—¬ ì¶©ëŒí•œ ì§€ì  ì°¾ê¸°
		if (GetWorld()->LineTraceSingleByChannel(HitResult, MouseLocation, End, ECC_Visibility))
		{
			//float Distance = FVector::Dist(HitResult.ImpactPoint, GetActorLocation());
			//GEngine->AddOnScreenDebugMessage(1, 0.2f,FColor::White,FString::Printf(TEXT("Distance: %f"),Distance));
			FVector TargetLocation = HitResult.ImpactPoint;
			Direction = (TargetLocation - GetActorLocation()).GetSafeNormal();
			//OwnerToMouseDirection = Direction;
			FRotator NewRot = Direction.Rotation();
			float yawOnly = NewRot.Yaw;

			SetActorRotation(FRotator(0.f, yawOnly, 0.f));
			//Controller->SetControlRotation(FRotator(0.f, yawOnly, 0.f));

			// 2) ì„œë²„ ê¶Œìœ„ ì—…ë°ì´íŠ¸(ë ˆì´íŠ¸ ì œí•œ)
			if (!HasAuthority())
			{
				//const float Now = GetWorld()->GetTimeSeconds();
				//const bool bigChange = FMath::Abs(yawOnly - LastSentAimYaw) > 1.5f;   // ê°ë„ ì„ê³„
				//const bool timeUp    = (Now - LastAimSendTime) > 0.06f;             // ì•½ 16Hz

				//if (bigChange || timeUp)
				{
					ServerSetAimYaw(yawOnly);
					//LastSentAimYaw   = NewYaw;
					//LastAimSendTime  = Now;
				}
			}
			else
			{
				// ë¦¬ìŠ¨ì„œë²„ í˜¸ìŠ¤íŠ¸(ê¶Œìœ„)ë„ ë³µì œ ë³€ìˆ˜ ê°±ì‹ (ë©€í‹°ì— í•„ìˆ˜)
				ReplicatedAimYaw = yawOnly;
			}
		}
	}
}

void AUzuha::OnRep_AimYaw()
{
	// ì†Œìœ  í´ë¼ëŠ” ë¡œì»¬ì—ì„œ ì´ë¯¸ ëŒë¦¬ê³  ìˆìœ¼ë‹ˆ ì œì™¸í•˜ê³ ,
	// ì‹œë®¬ë ˆì´í‹°ë“œ í”„ë¡ì‹œë“¤ë§Œ ì„œë²„ ê°’ìœ¼ë¡œ íšŒì „ì‹œí‚´
	if (!IsLocallyControlled())
	{
		SetActorRotation(FRotator(0.f, ReplicatedAimYaw, 0.f));
	}
}

void AUzuha::ServerSetAimYaw_Implementation(float NewYaw)
{
	ReplicatedAimYaw = NewYaw;
	// ì„œë²„ ê¶Œìœ„ë¡œ ì‹¤ì œ íšŒì „ ì ìš©
	SetActorRotation(FRotator(0.f, ReplicatedAimYaw, 0.f));
}


void AUzuha::Server_TryAttack_Implementation(const FVector_NetQuantizeNormal& ShootDir)
{
	Multicast_OnHitFX(); // ì´í™íŠ¸ ë¸Œë¡œë“œìºìŠ¤íŠ¸
	DoAttackTrace_Server(ShootDir);
}

void AUzuha::DoAttackTrace_Server(const FVector& ShootDir)
{
	//auto* PC = Cast<AUzuhaController>(GetController());
	if (!PC) return;
	
	// ë³´ì•ˆ/ì¹˜íŠ¸ ë°©ì§€: ì„œë²„ ê¸°ì¤€ ìœ„ì¹˜/ë°©í–¥ ì‚¬ìš©
	CurrentTarget = FindNearestEnemy_Registry(900.0f); // ì‹œì•¼ ë²”ìœ„ë‘ ë§ì¶°ì¤˜ì•¼ëŒ
	if (!CurrentTarget) return;
	
	//const FVector Start = GetActorLocation();
	const FVector Start = GetActorLocation();
	// const FVector End   = Start + ShootDir.GetSafeNormal() * AttackRange;
	const FVector End   = CurrentTarget->GetActorLocation();
	Multicast_DebugLine(Start,End);
	//DrawDebugLine(GetWorld(), Start, End, FColor::White, false, 0.4f, 0, 2.0f);
	UGameplayStatics::ApplyDamage(
			CurrentTarget,
			10.f,
			PC,
			this,
			UDamageType::StaticClass()
			);
}


void AUzuha::SpawnPing()//FVector Location)
{
	if (HasAuthority())
	{
		Multicast_SpawnPing();
	}
	else
	{
		Server_SpawnPing();
	}
}

void AUzuha::Server_SpawnPing_Implementation()
{
	Multicast_SpawnPing();
}

void AUzuha::Multicast_SpawnPing_Implementation()
{
	FActorSpawnParameters Params;
	Params.SpawnCollisionHandlingOverride = ESpawnActorCollisionHandlingMethod::AlwaysSpawn;
	// (ì„ íƒ) ì˜¤ë„ˆëŠ” ëˆ„ê°€ ëˆŒë €ëŠ”ì§€ ì‹ë³„ìš©ìœ¼ë¡œë§Œ ì„¤ì •
	Params.Owner = this;

	PingActor =  GetWorld()->SpawnActor<APingActor>(PingActorClass, SpawnLocation, FRotator::ZeroRotator, Params);
}

void AUzuha::TrySpawnTank()//FVector_NetQuantize Location)
{
	if (HasAuthority())
	{
		Multicsat_SpawnTank();	
	}
	else
	{
		Server_SpawnTank();
	}
}

void AUzuha::Multicsat_SpawnTank_Implementation()//FVector_NetQuantize Location)
{
	if (CommandCenterInstance)
	{
		CommandCenterInstance->MultiCast_SpawnTank(SpawnLocation);
	}
	else
	{
		GEngine->AddOnScreenDebugMessage(-1,2.0f, FColor::Red,
			TEXT("[Uzuha] CommandCenter is null"));
	}
}

void AUzuha::Server_SpawnTank_Implementation()//FVector_NetQuantize Location)
{
	Multicsat_SpawnTank();
}


void AUzuha::Multicast_OnHitFX_Implementation()//const FVector_NetQuantize& HitLocation)
{
	// TODO: íŒŒí‹°í´/ì‚¬ìš´ë“œ ì¬ìƒ (ì„œë²„/í´ë¼ ëª¨ë‘ ë³´ì´ê²Œ)
	// UGameplayStatics::SpawnEmitterAtLocation(GetWorld(), ImpactFX, HitLocation);
	AttackState = EAttackState::Shoot;
	AnimInstance->SetAnimState(EAnimState::Shoot);
	
	// Muzzle ì†Œì¼“ì— ë¶™ì—¬ ì¬ìƒ: ìœ„ì¹˜/íšŒì „ì„ ì†Œì¼“ì— 'ìŠ¤ëƒ…' (ì •í™•íˆ ì¼ì¹˜)
	UNiagaraComponent* NC = UNiagaraFunctionLibrary::SpawnSystemAttached(
		MuzzleFlashFX,
		GetMesh(),                   // ë¶™ì¼ ì»´í¬ë„ŒíŠ¸ (ë¬´ê¸° ë©”ì‰¬ë©´ ê·¸ìª½ìœ¼ë¡œ êµì²´)
		FName("Muzzle_01"),             // ì†Œì¼“/ë³¸ ì´ë¦„ (ëŒ€ì†Œë¬¸ì ì •í™•íˆ!)
		FVector::ZeroVector,         // ì†Œì¼“ ê¸°ì¤€ ìœ„ì¹˜ ì˜¤í”„ì…‹
		FRotator::ZeroRotator,       // ì†Œì¼“ ê¸°ì¤€ íšŒì „ ì˜¤í”„ì…‹
		EAttachLocation::SnapToTarget, // ì†Œì¼“ íŠ¸ëœìŠ¤í¼ì— ìŠ¤ëƒ…
		/*bAutoDestroy=*/true,       // ëë‚˜ë©´ ìë™ íŒŒê´´
		/*bAutoActivate=*/true
	);
	
	/*
	auto socket = 
	GetMesh();*/
	// UGameplayStatics::SpawnEmitterAtLocation(GetWorld(), MuzzleFlashFX	, GetMesh()->GetSocketByName("Muzzle")->GetSocketLocation());
	
	//AnimationComponent->server_playon
	if (AnimationComponent->MontageMapData != nullptr)
	{
		AnimationComponent->PlayByName("Shoot", 1.0f);
	}
	else
	{
		GEngine->AddOnScreenDebugMessage(-1 ,3.0f, FColor::Red, TEXT("[AnimationComponent] MontageMapData = null"));
	}
	SoundComponent->PlayHandle(ESoundName::effect_Shoot,this);
}

void AUzuha::Multicast_DebugLine_Implementation(FVector_NetQuantize Start, FVector_NetQuantize End, FColor Color,
                                                float LifeTime, float Thickness)
{
	if (GetNetMode() == NM_DedicatedServer) return;
	//DrawDebugLine(GetWorld(), Start, End, Color, /*bPersistentLines=*/false, LifeTime, /*DepthPriority=*/0, Thickness);
}



void AUzuha::LM_Press()
{
	//auto* PC = Cast<AUzuhaController>(GetController());
	if (!PC)
	{
		GEngine->AddOnScreenDebugMessage(-1, 1.0f, FColor::Red,TEXT("Controller = null"));
		return;
	}
	//  ìˆœì„œ ì¤‘ìš”í•¨
	// 1. ë•…ì—ì„œ ë°©í–¥ í™•ì¸í•˜ê¸°, 2. ë°”ë¼ë³´ê³ ìˆëŠ”ë°©í–¥ ë¼ì¸ íŠ¸ë ˆì´ìŠ¤
	if (PlayerState == EPlayerState::Normal)
	{
	}
	else if (PlayerState == EPlayerState::Attack)
	{
		if (!bCanAttack) return;
		bCanAttack = false;
		bIsAutoAttack= true;
		GetWorld()->GetTimerManager().SetTimer(AttackTimerHandle,this,
			&AUzuha::Multicast_OnHitFX, AttackCoolTime, true);

		GetWorld()->GetTimerManager().ClearTimer(AttackDelayHandle);
		GetWorld()->GetTimerManager().SetTimer(AttackDelayHandle, this,
			&AUzuha::AttackDealyReset, AttackCoolTime- 0.05f,false);
		
		GetMouseGroundLocation(); // 1
		//CheckFrontDistance(); // 2
		
		if (HasAuthority())
		{
			Multicast_OnHitFX(); // ì´í™íŠ¸ ë¸Œë¡œë“œìºìŠ¤íŠ¸
			DoAttackTrace_Server(Direction); // ë¦¬ìŠ¨ì„œë²„ í˜¸ìŠ¤íŠ¸ì˜ ë¡œì»¬ê³µê²©
		}
		else
		{
			Server_TryAttack(Direction); // ì›ê²©ì˜ í´ë¼ -> ì„œë²„ RPCí˜¸ì¶œ
		}
	}
	else if (PlayerState == EPlayerState::Order)
	{
		if (OrderWidget) return;
		FHitResult Hit;
		FCollisionQueryParams Params;
		Params.AddIgnoredActor(this);
		if (APawn* Pawn = PC->GetPawn()) Params.AddIgnoredActor(Pawn);

		FVector MouseWorldOrigin, MouseWorldDir;
		if (PC->DeprojectMousePositionToWorld(MouseWorldOrigin, MouseWorldDir))
		{
			const FVector Start = MouseWorldOrigin; // ì¹´ë©”ë¼ ê·¼ì²˜(í´ë¦¬í•‘ëœ ë§ˆìš°ìŠ¤ ê´‘ì„  ì‹œì‘ì )
			const FVector End = Start + MouseWorldDir * 2000; // ì»¤ì„œ ë°©í–¥ìœ¼ë¡œ ì¶©ë¶„íˆ ë©€ë¦¬

			const bool bHit = GetWorld()->LineTraceSingleByChannel(Hit, Start, End, ECC_Visibility, Params);
			//DrawDebugLine(GetWorld(), Start, End, FColor::Green, false, 0.5f);

			if (bHit)
			{
				SpawnLocation = Hit.ImpactPoint;
				//GEngine->AddOnScreenDebugMessage(-1, 1.0f, FColor::Green, TEXT("SpawnOrderWidget"));

				OrderWidget = GetWorld()->SpawnActor<AOrderWidgetActor>(OrderWidgetActorClass, SpawnLocation,
				                                                        FRotator::ZeroRotator);
				OrderWidget->SetPlayer(this);
				SpawnPing();
			}
			else
			{
				GEngine->AddOnScreenDebugMessage(-1, 1.0f, FColor::Red,TEXT("ìƒì„±ë¶ˆê°€"));
			}
		}
	}
}

void AUzuha::LM_Release()
{
	if (bIsAutoAttack) // ìë™ê³µê²©ì¤‘ì´ë¼ë©´
	{
		bIsAutoAttack = false;
		GetWorld()->GetTimerManager().ClearTimer(AttackTimerHandle);
	}
}

void AUzuha::RM_Press()
{
	//auto* PC = Cast<AUzuhaController>(GetController());
	if (!PC)
	{
		GEngine->AddOnScreenDebugMessage(-1, 1.0f, FColor::Red,TEXT("PC ì—†ìŒ"));
		return;
	}

	if (PlayerState == EPlayerState::Order)
	{
		DestroyOrderWidget(false);
	}
	bRMPressed = true;
	SetAttackModeLook(true);
	CursorWidget->ChangeCursorIcon(ECursorType::Attack);
	PlayerState = EPlayerState::Attack;
}

void AUzuha::RM_Release()
{
	//auto* PC = Cast<AUzuhaController>(GetController());
	if (!PC) return;
	bRMPressed = false;
	if (bIsAutoAttack) // ìë™ê³µê²©ì¤‘ì´ë¼ë©´
	{
		bIsAutoAttack = false;
		GetWorld()->GetTimerManager().ClearTimer(AttackTimerHandle);
	}
	SetAttackModeLook(false);
	CursorWidget->ChangeCursorIcon(ECursorType::Normal);
	PlayerState = EPlayerState::Normal;
	//GEngine->AddOnScreenDebugMessage(-1, 1.0f, FColor::White,TEXT("RM Release"));
}

void AUzuha::Ctrl_Press()
{
	if (!IsLocallyControlled()) return;
	if (bIsAutoAttack) // ìë™ê³µê²©ì¤‘ì´ë¼ë©´
	{
		bIsAutoAttack = false;
		GetWorld()->GetTimerManager().ClearTimer(AttackTimerHandle);
	}
	//if (CursorWidget == nullptr)
	CursorWidget->ChangeCursorIcon(ECursorType::Order);
	PlayerState = EPlayerState::Order;
}

void AUzuha::Ctrl_Relesae()
{
	CursorWidget->ChangeCursorIcon(ECursorType::Normal);
	PlayerState = EPlayerState::Normal;
	//PlayerWidget->DestoryOrderWidget();
	DestroyOrderWidget(false);
}

void AUzuha::DestroyOrderWidget(bool _isClick)
{
	if (OrderWidget)
	{
		OrderWidget->Destroy();
		OrderWidget=nullptr;
		
		PingActor->Destroy();
		PingActor = nullptr;
	}
	if(_isClick)
	{
		TrySpawnTank();
	}
}

void AUzuha::ListWidgetInit()
{
	PlayerListWidget->TryInitPlayerList();
}

void AUzuha::MultiCast_OnDeath_Implementation()
{
	// DeatAnim
}

void AUzuha::HandleDeath()
{
	GEngine->AddOnScreenDebugMessage(-1, 1.0f, FColor::White,TEXT("Death Uzuha"));
	
}

void AUzuha::RegisterRevealer()
{
	if (auto* FOW = GetWorld()->GetSubsystem<UFogOfWarSubsystem>())
	{
		if (VisionRevealerComponent)
		{
			int32 TeamID = 0;
			VisionRevealerComponent->SetCurrentTeam(TeamID);
			FOW->RegisterRevealer(VisionRevealerComponent, VisionRevealerComponent->GetScaledSphereRadius(), TeamID);
		}
	}
	else
	{
		GEngine->AddOnScreenDebugMessage(-1, 5.0f, FColor::Red,TEXT("[Enemy] FOWsubsystem ì—†ìŒ"));
	}

	if (HasAuthority())
	{
		//PlayerWidget->PlayerList->Multicast_InitPlayerList();
	}
}

void AUzuha::EnsureLocalUI()
{
	// âœ… UI/ì…ë ¥ ì„¸íŒ…ì€ "ë¡œì»¬ë¡œ ì†Œìœ í•œ í´ë¼ì´ì–¸íŠ¸"ì—ì„œë§Œ!
	if (!IsLocallyControlled()) return;
	{
			if (!PC) PC = Cast<AUzuhaController>(GetController());

			if (PC)
			{
				//GEngine->AddOnScreenDebugMessage(-1, 5.0f,FColor::Green,FString::Printf(TEXT("Contrlller : %s"), *PC->GetName()));
				PC->bShowMouseCursor = true;
				PC->bEnableClickEvents = true;
				PC->bEnableMouseOverEvents = true;
				// ì…ë ¥ ëª¨ë“œ: ê²Œì„(í‚¤ë³´ë“œ) + ì»¤ì„œ í‘œì‹œ
				/*
				FInputModeGameOnly Mode;
				Mode.SetConsumeCaptureMouseDown(false);
				Controller->SetInputMode(Mode);*/

				//FInputModeGameOnly Mode;
				FInputModeGameAndUI Mode;
				Mode.SetHideCursorDuringCapture(false);
				Mode.SetLockMouseToViewportBehavior(EMouseLockMode::DoNotLock);
				PC->SetInputMode(Mode);
				if (PC && CursorWidgetClass)
				{
					CursorWidget = CreateWidget<UCursorWidget>(PC, CursorWidgetClass, NAME_None);
					PC->SetMouseCursorWidget(EMouseCursor::Default, CursorWidget); // ì†Œí”„íŠ¸ì›¨ì–´ ì»¤ì„œ
					//CursorWidget->ChangeCursorColor(ECursorType::Normal);
					// ì»¤ì„œ ì´ë¯¸ì§€ë¥¼ ìœ„ì ¯ìœ¼ë¡œ êµì²´
				}
				
				if (PC && PlayerWidgetClass)
				{
					PlayerWidget = CreateWidget<UPlayerWidget>(PC, PlayerWidgetClass, NAME_None);
					PlayerWidget->AddToViewport();
				}
				if (PC&&PlayerListWidgetClass)
				{
					PlayerListWidget = CreateWidget<UPlayerListWidget>(PC, PlayerListWidgetClass, NAME_None);
					PlayerListWidget->AddToViewport();
					//PlayerListWidget->Multicast_PlayerListRebuild();
				}
			}

		
		if (HealthWidget)
		{
			HealthWidget->InitWidget();
			//HealthComponent->HealthInitialize(50.f); ê°ì ìºë¦­í„°ì—ì„œ í• ê²¨
			if (UUserWidget* UW = HealthWidget->GetUserWidgetObject())              // âœ… ì¸ìŠ¤í„´ìŠ¤ ì–»ê¸°
			{
				if (UEnemyHealthWidget* EH = Cast<UEnemyHealthWidget>(UW))
				{
					//EH->SetHeatlhBarColor(FColor::Blue);
					HealthComponent->HPBarWidgetInstance = EH->GetBar();            // âœ… ë°” í¬ì¸í„° ì—°ê²°
					//HealthComponent->HPBarWidgetInstance->
					HealthComponent->UpdateHealthUI();                             // ì´ˆê¸° ê°’ ê°±ì‹ 
					//HealthWidget->PrimaryComponentTick.TickGroup = TG_PostUpdateWork;
				}
			}
			else
			{
				GEngine->AddOnScreenDebugMessage(-1, 3.0F, FColor::Red, TEXT("[Enemy] Widget is null"));
			}
		}
	
		
	}
}

AActor* AUzuha::FindNearestEnemy_Registry(float MaxRadius)
{
	float ClosestDist = FLT_MAX;
	AActor* Closest = nullptr;
	//GEngine->AddOnScreenDebugMessage(-1, 1.0f, FColor::Red, TEXT("FindNear"));
	for (TActorIterator<AActor> It(GetWorld()); It; ++It)
	{
		if (It->ActorHasTag("Enemy"))
		{
			float Dist = FVector::Dist(GetActorLocation(), It->GetActorLocation());
			//DrawDebugLine(GetWorld(), GetActorLocation(), It->GetActorLocation(), FColor::Blue, false, 1.0f);
			if (Dist < ClosestDist)
			{
				Closest = *It;
				ClosestDist = Dist;
			}
		}
	}
	return Closest;
}

void AUzuha::CheckFrontDistance()
{
	FHitResult HitResult;
	FVector EndPoint = GetActorLocation() + (Direction * AttackRange);
	if (GetWorld()->LineTraceSingleByChannel(HitResult, GetActorLocation(), EndPoint, ECC_Visibility))
	{
		if (ABaseEnemy* hit = Cast<ABaseEnemy>(HitResult.GetActor()))
		{
			// ì—¬ê¸°ì„œ ë³´ì´ëŠ” ìƒíƒœì¸ì§€ ê²€ì‚¬í•˜ê¸°
			//GEngine->AddOnScreenDebugMessage(-1, 2.0f, FColor::Cyan, FString::Printf(TEXT("Hit %s"), *hit->GetName()));
			EndPoint = hit->GetActorLocation();
			//enemypoiunt = EndPoint;
			//hit->GetDamaged(10.0f);
			//SetNewCameraPivot();
			/*
			bTargetCamOn = true;
			CameraPoint = EndPoint;
			
			if (GetWorld()->GetTimerManager().IsTimerActive(CameraTimer))
			{
				GetWorld()->GetTimerManager().ClearTimer(CameraTimer);
			}
			GetWorld()->GetTimerManager().SetTimer(CameraTimer,
			                                       this,
			                                       &AUzuha::ResetCameraPivot, 1.5f, false);*/
		}
	}
	else
	{
		GEngine->AddOnScreenDebugMessage(-1, 2.0f, FColor::Red,TEXT("No Hit"));
		//CameraPoint = EndPoint;
	}
	//DrawDebugLine(GetWorld(), GetActorLocation(), EndPoint, FColor::Red, false, 1.0f);
}

void AUzuha::SetNewCameraPivot()
{
	FVector CameraDirection = (CameraPoint - GetActorLocation()).GetSafeNormal();
	//DrawDebugLine(GetWorld(),GetActorLocation(), CameraPoint)
	float dir = FVector::Dist(CameraDirection, GetActorLocation());

	CameraPoint = GetActorLocation() + (CameraDirection * (dir * 0.5f));
	//CameraPivot->UpdateCameraLocation(lerpLocation);
	//CameraPivot->SetWorldLocation(lerpLocation);
	//CameraPoint =  lerpLocation;

	// ëª‡ ì´ˆ ë’¤ì— ì›ë˜ ìœ„ì¹˜ë¡œ ë³µê·€ë˜ë„ë¡ í•´ì•¼ëŒ
}

void AUzuha::ResetCameraPivot()
{
	//CameraPivot->SetRelativeLocation(FVector::ZeroVector);
	bTargetCamOn = false;
}


void AUzuha::SetAttackModeLook(bool bEnable)
{
	UCharacterMovementComponent* Move = GetCharacterMovement();
	if (!Move) return;

	if (bEnable)
	{
		// â”€â”€ ë¶„ë¦¬ ëª¨ë“œ: ì´ë™ì€ WASDëŒ€ë¡œ, íšŒì „ì€ ì»¨íŠ¸ë¡¤ëŸ¬ Yaw(=ìš°ë¦¬ê°€ ê³„ì‚°)ë¡œ
		Move->bOrientRotationToMovement = false;
		Move->bUseControllerDesiredRotation = true; // íšŒì „ì„ ì»¨íŠ¸ë¡¤ëŸ¬ Yawë¡œ êµ¬ë™
		bUseControllerRotationYaw = false; // ìºë¦­í„°ê°€ ì»¨íŠ¸ë¡¤ëŸ¬ Yawë¥¼ 'ì§ì ‘' ì¦‰ì‹œ ë°˜ì˜í•˜ëŠ” ê±´ X
	}
	else
	{
		// â”€â”€ ê²°í•© ëª¨ë“œ: ì´ë™ ë°©í–¥ì„ ë°”ë¼ë³´ê¸°
		Move->bOrientRotationToMovement = true;
		Move->bUseControllerDesiredRotation = false;
		bUseControllerRotationYaw = false; // íƒ‘ë·°ì—ì„  ë³´í†µ false ìœ ì§€
	}
}

void AUzuha::GetMouseGroundLocation()
{
	//auto* PC = Cast<AUzuhaController>(GetController());
	if (!PC) return;
	FVector MouseLocation, MouseDirection;
	// ğŸ”¹ ë§ˆìš°ìŠ¤ì˜ ì›”ë“œ ìœ„ì¹˜ì™€ ë°©í–¥ì„ ì–»ê¸°
	if (PC->DeprojectMousePositionToWorld(MouseLocation, MouseDirection))
	{
		FHitResult HitResult;
		FVector End = MouseLocation + (MouseDirection * 10000.0f);

		// ğŸ”¹ ë§ˆìš°ìŠ¤ ë°©í–¥ìœ¼ë¡œ ë ˆì´ìºìŠ¤íŠ¸í•˜ì—¬ ì¶©ëŒí•œ ì§€ì  ì°¾ê¸°
		if (GetWorld()->LineTraceSingleByChannel(HitResult, MouseLocation, End, ECC_Visibility))
		{
			float Distance = FVector::Dist(HitResult.ImpactPoint, GetActorLocation());
			//GEngine->AddOnScreenDebugMessage(1, 0.2f, FColor::White, FString::Printf(TEXT("Distance: %f"), Distance));
			FVector TargetLocation = HitResult.ImpactPoint;
			TargetLocation.Z = GetActorLocation().Z;
			//TargetLocation.X += 10.0f;
			Direction = (TargetLocation - GetActorLocation()).GetSafeNormal();
			//OwnerToMouseDirection = Direction;
			FRotator NewRot = Direction.Rotation();
			float yawOnly = NewRot.Yaw;
			SetActorRotation(FRotator(0.f, yawOnly, 0.f));
		}
	}
}

void AUzuha::Q_Press()
{
}

void AUzuha::Q_Relesae()
{
}


void AUzuha::OrderSpawn(const FVector& _point)
{
}


void AUzuha::UpdateSpringArm(float _delta)
{
	/*
	if (SpringArm->TargetArmLength >= DefaultSpringArm ||
		SpringArm->TargetArmLength <= DefaultSpringArm - 150) return;
	*/
	static float speed = 1000.f;
	if (bRMPressed)
	{
		SpringArmAlpha += _delta * speed;
	}
	else
	{
		SpringArmAlpha -= _delta * speed;
	}
	SpringArmAlpha = FMathf::Clamp(SpringArmAlpha, 0.0f, 120.0f);
	//float newSRL = FMath::Clamp(SpringArmAlpha, 0, 150);

	//CameraPivot->SpringArm->TargetArmLength = DefaultSpringArm + SpringArmAlpha;
	SpringArm->TargetArmLength = DefaultSpringArm + SpringArmAlpha;
}

void AUzuha::AttackDealyReset()
{
	bCanAttack = true;
}
